language: node_js
node_js:
- v8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- -i --coverage
env:
  global:
  - CXX=g++-4.8
  - MONGODB_URI=mongodb://localhost/brighton-fgc-api-dev
