version: '3.7'
services:
  hbk-api:
    build:
      context: .
    command: sh -c "yarn && yarn dev"
    volumes:
      - .:/app
    links:
      - "hbk-mongo:hbk-mongo"
    environment:
      - NODE_ENV=development
      - PORT=9000
      - MONGODB_URI=mongodb://root:password@hbk-mongo/hbk-setup?authSource=admin
      - SEED_DB=
    ports:
      - 9000:9000
  hbk-mongo:
    image: mongo:latest
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - hbk-mongo:/data/db
  hbk-mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=hbk-mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    links:
      - "hbk-mongo:hbk-mongo"
volumes:
  hbk-mongo:
